services:
  redis:
    image: redis:7.4.2
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  nats:
    image: nats:2.10
    container_name: nats-container
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    environment:
      - NATS_JETSTREAM=true
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf
      - nats_data:/data
    command: --config /etc/nats/nats-server.conf
    networks:
      - backend

  mongo:
    image: mongo:8.0
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 20s
      retries: 10
      start_period: 30s
      timeout: 10s
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang-api:latest
    container_name: golang-api
    environment:
      CACHE_PASSWORD: "${CACHE_PASSWORD}"
      CACHE_HOST: "${CACHE_HOST}"
      CACHE_DB_NAME: "${CACHE_DB_NAME}"
      SQLDB_USER: "${SQLDB_USER}"
      SQLDB_PASSWORD: "${SQLDB_PASSWORD}"
      SQLDB_HOST: "${SQLDB_HOST}"
      SQLDB_NAME: "${SQLDB_NAME}"
      SQLDB_MAX_IDLE_CONNECTIONS: "${SQLDB_MAX_IDLE_CONNECTIONS}"
      SQLDB_MAX_OPEN_CONNECTIONS: "${SQLDB_MAX_OPEN_CONNECTIONS}"
      SQLDB_DISABLE_TLS: "${SQLDB_DISABLE_TLS}"
      NOSQLDB_USER: "${NOSQLDB_USER}"
      NOSQLDB_PASSWORD: "${NOSQLDB_PASSWORD}"
      NOSQLDB_HOST: "${NOSQLDB_HOST}"
      NOSQLDB_NAME: "${NOSQLDB_NAME}"
      PORT: "${PORT}"
      ALLOWED_ORIGINS: "${ALLOWED_ORIGINS}"
      MESSAGING_USER: "${MESSAGING_USER}"
      MESSAGING_PASSWORD: "${MESSAGING_PASSWORD}"
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:

volumes:
  redis_data:
  mysql_data:
  mongo_data:
  nats_data:
